CREATE TABLE CURSO(
CODCURSO SERIAL PRIMARY KEY,
NOMECURSO VARCHAR (80) NOT NULL UNIQUE
);
DELETE TABLE ALUNO;
CREATE TABLE SEXO(
CODSEXO SERIAL PRIMARY KEY,
NOMESEXO VARCHAR(9) NOT NULL UNIQUE
);
CREATE TABLE RUA(
CODRUA SERIAL PRIMARY KEY,
NOMERUA VARCHAR (80) NOT NULL
);
CREATE TABLE BAIRRO(
CODBAIRRO SERIAL PRIMARY KEY,
NOMEBAIRRO VARCHAR (80) NOT NULL
);
CREATE TABLE CEP(
CODCEP SERIAL PRIMARY KEY,
NUMEROCEP VARCHAR (80) NOT NULL UNIQUE
);
CREATE TABLE ESTADO(
CODESTADO SERIAL PRIMARY KEY,
NOMEESTADOSIGLA VARCHAR (2) NOT NULL UNIQUE
);
CREATE TABLE CIDADE(
CODCIDADE SERIAL PRIMARY KEY,
NOMECIDADE VARCHAR (80) NOT NULL,
CODESTADO_FK INTEGER REFERENCES ESTADO(CODESTADO)  ON
DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ALUNO(
CODALUNO SERIAL PRIMARY KEY,
NOMECALUNO VARCHAR (80) NOT NULL,
CODCURSO_FK INTEGER REFERENCES CURSO(CODCURSO) MATCH SIMPLE ON
	DELETE CASCADE ON UPDATE CASCADE,

CODSEXO_FK INTEGER REFERENCES SEXO(CODSEXO) MATCH SIMPLE ON
	DELETE CASCADE ON UPDATE CASCADE,

CODRUA_FK INTEGER REFERENCES RUA(CODRUA) MATCH SIMPLE ON
	DELETE CASCADE ON UPDATE CASCADE,

CODBAIRRO_FK INTEGER REFERENCES BAIRRO(CODBAIRRO) MATCH SIMPLE ON
	DELETE CASCADE ON UPDATE CASCADE,

CODCEP_FK INTEGER REFERENCES CEP(CODCEP) MATCH SIMPLE ON
	DELETE CASCADE ON UPDATE CASCADE,

CODCIDADE_FK INTEGER REFERENCES CIDADE(CODCIDADE) MATCH SIMPLE ON
	DELETE CASCADE ON UPDATE CASCADE
);



